package com.example.bootiful_javafx;

import org.springframework.aot.hint.TypeReference;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.HashSet;
import java.util.List;

@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
class Lister {

    @EventListener
    void on(ApplicationReadyEvent event) throws Exception {
        var missing = new HashSet<TypeReference>();
        var clzzes = HintsUtils.findClassesInPackage("com.sun.prism.shader");
        for (var c : PRISM_SHADERS) {
            var tr = TypeReference.of(c);
            if (!clzzes.contains(tr))
                missing.add(tr);
        }
        for (var m : missing)
            IO.println("missing > " + m );
    }

    private static final List<Class<?>> PRISM_SHADERS = List.of(
            com.sun.prism.shader.AlphaOne_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaOne_Color_Loader.class,
            com.sun.prism.shader.AlphaOne_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaOne_ImagePattern_Loader.class,
            com.sun.prism.shader.AlphaOne_LinearGradient_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaOne_LinearGradient_Loader.class,
            com.sun.prism.shader.AlphaOne_RadialGradient_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaOne_RadialGradient_Loader.class,
            com.sun.prism.shader.AlphaTextureDifference_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaTextureDifference_Color_Loader.class,
            com.sun.prism.shader.AlphaTextureDifference_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaTextureDifference_ImagePattern_Loader.class,
            com.sun.prism.shader.AlphaTextureDifference_LinearGradient_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaTextureDifference_LinearGradient_Loader.class,
            com.sun.prism.shader.AlphaTextureDifference_RadialGradient_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaTextureDifference_RadialGradient_Loader.class,
            com.sun.prism.shader.AlphaTexture_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaTexture_Color_Loader.class,
            com.sun.prism.shader.AlphaTexture_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaTexture_ImagePattern_Loader.class,
            com.sun.prism.shader.AlphaTexture_LinearGradient_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaTexture_LinearGradient_Loader.class,
            com.sun.prism.shader.AlphaTexture_RadialGradient_AlphaTest_Loader.class,
            com.sun.prism.shader.AlphaTexture_RadialGradient_Loader.class,
            com.sun.prism.shader.DrawCircle_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawCircle_Color_Loader.class,
            com.sun.prism.shader.DrawCircle_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawCircle_ImagePattern_Loader.class,
            com.sun.prism.shader.DrawCircle_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawCircle_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawCircle_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawCircle_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawCircle_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawCircle_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.DrawCircle_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawCircle_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawCircle_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawCircle_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawCircle_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawCircle_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.DrawEllipse_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawEllipse_Color_Loader.class,
            com.sun.prism.shader.DrawEllipse_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawEllipse_ImagePattern_Loader.class,
            com.sun.prism.shader.DrawEllipse_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawEllipse_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawEllipse_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawEllipse_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawEllipse_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawEllipse_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.DrawEllipse_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawEllipse_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawEllipse_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawEllipse_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawEllipse_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawEllipse_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.DrawPgram_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawPgram_Color_Loader.class,
            com.sun.prism.shader.DrawPgram_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawPgram_ImagePattern_Loader.class,
            com.sun.prism.shader.DrawPgram_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawPgram_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawPgram_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawPgram_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawPgram_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawPgram_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.DrawPgram_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawPgram_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawPgram_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawPgram_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawPgram_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawPgram_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.DrawRoundRect_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawRoundRect_Color_Loader.class,
            com.sun.prism.shader.DrawRoundRect_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawRoundRect_ImagePattern_Loader.class,
            com.sun.prism.shader.DrawRoundRect_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawRoundRect_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawRoundRect_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawRoundRect_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawRoundRect_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawRoundRect_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.DrawRoundRect_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawRoundRect_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawRoundRect_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawRoundRect_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawRoundRect_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawRoundRect_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_Color_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_ImagePattern_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.DrawSemiRoundRect_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.FillCircle_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.FillCircle_Color_Loader.class,
            com.sun.prism.shader.FillCircle_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.FillCircle_ImagePattern_Loader.class,
            com.sun.prism.shader.FillCircle_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.FillCircle_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.FillCircle_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillCircle_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.FillCircle_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillCircle_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.FillCircle_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.FillCircle_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.FillCircle_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillCircle_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.FillCircle_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillCircle_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.FillEllipse_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.FillEllipse_Color_Loader.class,
            com.sun.prism.shader.FillEllipse_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.FillEllipse_ImagePattern_Loader.class,
            com.sun.prism.shader.FillEllipse_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.FillEllipse_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.FillEllipse_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillEllipse_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.FillEllipse_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillEllipse_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.FillEllipse_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.FillEllipse_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.FillEllipse_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillEllipse_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.FillEllipse_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillEllipse_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.FillPgram_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.FillPgram_Color_Loader.class,
            com.sun.prism.shader.FillPgram_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.FillPgram_ImagePattern_Loader.class,
            com.sun.prism.shader.FillPgram_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.FillPgram_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.FillPgram_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillPgram_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.FillPgram_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillPgram_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.FillPgram_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.FillPgram_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.FillPgram_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillPgram_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.FillPgram_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillPgram_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.FillRoundRect_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.FillRoundRect_Color_Loader.class,
            com.sun.prism.shader.FillRoundRect_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.FillRoundRect_ImagePattern_Loader.class,
            com.sun.prism.shader.FillRoundRect_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.FillRoundRect_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.FillRoundRect_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillRoundRect_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.FillRoundRect_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillRoundRect_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.FillRoundRect_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.FillRoundRect_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.FillRoundRect_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillRoundRect_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.FillRoundRect_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.FillRoundRect_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.Mask_TextureRGB_AlphaTest_Loader.class,
            com.sun.prism.shader.Mask_TextureRGB_Loader.class,
            com.sun.prism.shader.Mask_TextureSuper_AlphaTest_Loader.class,
            com.sun.prism.shader.Mask_TextureSuper_Loader.class,
            com.sun.prism.shader.Solid_Color_AlphaTest_Loader.class, com.sun.prism.shader.Solid_Color_Loader.class,
            com.sun.prism.shader.Solid_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_ImagePattern_Loader.class,
            com.sun.prism.shader.Solid_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.Solid_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.Solid_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.Solid_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.Solid_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.Solid_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_RadialGradient_REPEAT_Loader.class,
            com.sun.prism.shader.Solid_TextureFirstPassLCD_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_TextureFirstPassLCD_Loader.class,
            com.sun.prism.shader.Solid_TextureRGB_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_TextureRGB_Loader.class,
            com.sun.prism.shader.Solid_TextureSecondPassLCD_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_TextureSecondPassLCD_Loader.class,
            com.sun.prism.shader.Solid_TextureYV12_AlphaTest_Loader.class,
            com.sun.prism.shader.Solid_TextureYV12_Loader.class,
            com.sun.prism.shader.Texture_Color_AlphaTest_Loader.class,
            com.sun.prism.shader.Texture_Color_Loader.class,
            com.sun.prism.shader.Texture_ImagePattern_AlphaTest_Loader.class,
            com.sun.prism.shader.Texture_ImagePattern_Loader.class,
            com.sun.prism.shader.Texture_LinearGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.Texture_LinearGradient_PAD_Loader.class,
            com.sun.prism.shader.Texture_LinearGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.Texture_LinearGradient_REFLECT_Loader.class,
            com.sun.prism.shader.Texture_LinearGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.Texture_LinearGradient_REPEAT_Loader.class,
            com.sun.prism.shader.Texture_RadialGradient_PAD_AlphaTest_Loader.class,
            com.sun.prism.shader.Texture_RadialGradient_PAD_Loader.class,
            com.sun.prism.shader.Texture_RadialGradient_REFLECT_AlphaTest_Loader.class,
            com.sun.prism.shader.Texture_RadialGradient_REFLECT_Loader.class,
            com.sun.prism.shader.Texture_RadialGradient_REPEAT_AlphaTest_Loader.class,
            com.sun.prism.shader.Texture_RadialGradient_REPEAT_Loader.class);
}